Set up testing environment
googleinterns/step220-2020 pull request #8
Opened 2020-09-01 13:43 UTC by tzavidas

2020-09-08 12:14 UTC, maxwbuckley approved these changes

2020-09-08 12:14 UTC, maxwbuckley commented on pom.xml
> +
Remove empty line? There is no empty line before the previous plugin

2020-09-09 11:05 UTC, semenovm requested changes

2020-09-09 11:05 UTC, semenovm commented on src/test/MIT.LICENSE
> +Copyright (c) 2008-2019 Pivotal Labs
Does this file belong here?

2020-09-09 11:05 UTC, semenovm commented on src/test/lib/jasmine-3.6.0/boot.js
> +/**
I believe jasmine-maven-plugin should download it automatically.

2020-09-09 11:05 UTC, semenovm commented on pom.xml
> +      </plugin>
Do you need this dependency, I thought you will use headless chrome instead?

2020-09-09 11:05 UTC, semenovm commented on src/test/SpecRunner.html
> +<!DOCTYPE html>
Is this file still required if you are using jasmin-plugin?

2020-09-16 13:03 UTC, maxwbuckley commented on src/test/MIT.LICENSE
> +Copyright (c) 2008-2019 Pivotal Labs
:D

2020-09-24 18:30 UTC, closed without merging